//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultyBlog.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MultyBlogDbEntityWeb : DbContext
    {
        public MultyBlogDbEntityWeb()
            : base("name=MultyBlogDbEntityWeb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblArticles> tblArticles { get; set; }
        public virtual DbSet<tblUsers> tblUsers { get; set; }
        public virtual DbSet<tblComments> tblComments { get; set; }
        public virtual DbSet<tblArticlesTags> tblArticlesTags { get; set; }
        public virtual DbSet<tblTags> tblTags { get; set; }
    }
}
