//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultyBlog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArticlesTags
    {
        public int ID { get; set; }
        public int ArticleID { get; set; }
        public int TagID { get; set; }
    
        public virtual tblArticles tblArticles { get; set; }
        public virtual tblTags tblTags { get; set; }
    }
}
