//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultyBlog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArticles
    {
        public tblArticles()
        {
            this.tblComments = new HashSet<tblComments>();
            this.tblArticlesTags = new HashSet<tblArticlesTags>();
        }
    
        public int ID { get; set; }
        public string Header { get; set; }
        public string Content { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual tblUsers tblUsers { get; set; }
        public virtual ICollection<tblComments> tblComments { get; set; }
        public virtual ICollection<tblArticlesTags> tblArticlesTags { get; set; }
    }
}
