//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultyBlog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComments
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int ArticleID { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual tblArticles tblArticles { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
