//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultyBlog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTags
    {
        public tblTags()
        {
            this.tblArticlesTags = new HashSet<tblArticlesTags>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int TagRequest { get; set; }
    
        public virtual ICollection<tblArticlesTags> tblArticlesTags { get; set; }
    }
}
